import { modelPath, hdrPath } from "@/lib/three/assets/paths";
import type {
  BaseAssetMetadata,
  CharacterAsset,
  EquipmentAsset,
  EnvironmentAsset,
  HDRAsset,
  PropAsset,
} from "@/lib/three/assets/types";

const DEFAULT_BOUNDS = {
  center: [0, 1, 0] as [number, number, number],
  size: [1, 2, 1] as [number, number, number],
  recommendedCameraDistance: 6,
  recommendedLookAt: [0, 1.2, 0] as [number, number, number],
};

export const assetRegistry = {
  characters: {
    "athlete-hero": {
      id: "athlete-hero",
      name: "Hero Athlete",
      category: "character",
      type: "character" as const,
      available: false,
      path: modelPath("characters", "athlete.glb"),
      thumbnail: "/images/placeholders/hero-fallback.svg",
      tier: "MEDIUM" as const,
      preload: true,
      preloadPriority: 1,
      interactive: true,
      motionId: "hero-athlete",
      transform: { position: [0, 0, 0], rotation: [0, 0, 0], scale: 1 },
      bounds: DEFAULT_BOUNDS,
      dimensions: [0.7, 1.85, 0.4],
      recommendedScale: 1,
      animations: ["idle", "breathing", "walk", "train", "pose"],
      animationClips: {
        IDLE: "idle",
        BREATHING: "breathing",
        WALK: "walk",
        TRAIN: "train",
        POSE: "pose",
      },
      defaultAnimation: "BREATHING" as const,
    } satisfies CharacterAsset,
  },

  equipment: {
    barbell: {
      id: "barbell",
      name: "Barbell",
      category: "equipment",
      type: "equipment" as const,
      equipmentCategory: "free-weight" as const,
      available: false,
      path: modelPath("equipment", "barbell.glb"),
      tier: "MEDIUM" as const,
      preload: false,
      preloadPriority: 3,
      motionId: "barbell",
      transform: { scale: 1 },
      bounds: {
        center: [0, 0.5, 0],
        size: [2.2, 0.3, 0.3],
        recommendedCameraDistance: 3,
        recommendedLookAt: [0, 0.5, 0],
      },
    } satisfies EquipmentAsset,
    dumbbell: {
      id: "dumbbell",
      name: "Dumbbell",
      category: "equipment",
      type: "equipment" as const,
      equipmentCategory: "free-weight" as const,
      available: false,
      path: modelPath("equipment", "dumbbell.glb"),
      tier: "MEDIUM" as const,
      preload: false,
      preloadPriority: 3,
      motionId: "dumbbell",
    } satisfies EquipmentAsset,
    kettlebell: {
      id: "kettlebell",
      name: "Kettlebell",
      category: "equipment",
      type: "equipment" as const,
      equipmentCategory: "free-weight" as const,
      available: false,
      path: modelPath("equipment", "kettlebell.glb"),
      tier: "MEDIUM" as const,
      preload: false,
      preloadPriority: 4,
    } satisfies EquipmentAsset,
    bench: {
      id: "bench",
      name: "Bench",
      category: "equipment",
      type: "equipment" as const,
      equipmentCategory: "strength" as const,
      available: false,
      path: modelPath("equipment", "bench.glb"),
      tier: "MEDIUM" as const,
      preload: false,
      preloadPriority: 4,
    } satisfies EquipmentAsset,
    plates: {
      id: "plates",
      name: "Weight Plates",
      category: "equipment",
      type: "equipment" as const,
      equipmentCategory: "free-weight" as const,
      available: false,
      path: modelPath("equipment", "plates.glb"),
      tier: "MEDIUM" as const,
      preload: false,
      preloadPriority: 4,
    } satisfies EquipmentAsset,
    "squat-rack": {
      id: "squat-rack",
      name: "Squat Rack",
      category: "equipment",
      type: "equipment" as const,
      equipmentCategory: "strength" as const,
      available: false,
      path: modelPath("equipment", "squat-rack.glb"),
      tier: "HIGH" as const,
      preload: false,
      preloadPriority: 5,
    } satisfies EquipmentAsset,
    "cable-machine": {
      id: "cable-machine",
      name: "Cable Machine",
      category: "equipment",
      type: "equipment" as const,
      equipmentCategory: "functional" as const,
      available: false,
      path: modelPath("equipment", "cable-machine.glb"),
      tier: "HIGH" as const,
      preload: false,
      preloadPriority: 5,
    } satisfies EquipmentAsset,
    rower: {
      id: "rower",
      name: "Rowing Machine",
      category: "equipment",
      type: "equipment" as const,
      equipmentCategory: "cardio" as const,
      available: false,
      path: modelPath("equipment", "rower.glb"),
      tier: "MEDIUM" as const,
      preload: false,
      preloadPriority: 5,
    } satisfies EquipmentAsset,
    treadmill: {
      id: "treadmill",
      name: "Treadmill",
      category: "equipment",
      type: "equipment" as const,
      equipmentCategory: "cardio" as const,
      available: false,
      path: modelPath("equipment", "treadmill.glb"),
      tier: "MEDIUM" as const,
      preload: false,
      preloadPriority: 6,
    } satisfies EquipmentAsset,
    bike: {
      id: "bike",
      name: "Assault Bike",
      category: "equipment",
      type: "equipment" as const,
      equipmentCategory: "cardio" as const,
      available: false,
      path: modelPath("equipment", "bike.glb"),
      tier: "MEDIUM" as const,
      preload: false,
      preloadPriority: 6,
    } satisfies EquipmentAsset,
    sled: {
      id: "sled",
      name: "Sled",
      category: "equipment",
      type: "equipment" as const,
      equipmentCategory: "functional" as const,
      available: false,
      path: modelPath("equipment", "sled.glb"),
      tier: "MEDIUM" as const,
      preload: false,
      preloadPriority: 6,
    } satisfies EquipmentAsset,
    "boxing-bag": {
      id: "boxing-bag",
      name: "Boxing Bag",
      category: "equipment",
      type: "equipment" as const,
      equipmentCategory: "functional" as const,
      available: false,
      path: modelPath("equipment", "boxing-bag.glb"),
      tier: "MEDIUM" as const,
      preload: false,
      preloadPriority: 6,
    } satisfies EquipmentAsset,
  },

  environments: {
    "gym-floor": {
      id: "gym-floor",
      name: "Gym Floor",
      category: "environment",
      type: "environment" as const,
      environmentCategory: "floor" as const,
      available: false,
      path: modelPath("environment", "gym-floor.glb"),
      tier: "MEDIUM" as const,
      preload: false,
      preloadPriority: 2,
    } satisfies EnvironmentAsset,
    "gym-walls": {
      id: "gym-walls",
      name: "Gym Walls",
      category: "environment",
      type: "environment" as const,
      environmentCategory: "wall" as const,
      available: false,
      path: modelPath("environment", "gym-walls.glb"),
      tier: "MEDIUM" as const,
      preload: false,
      preloadPriority: 2,
    } satisfies EnvironmentAsset,
    "gym-ceiling": {
      id: "gym-ceiling",
      name: "Gym Ceiling",
      category: "environment",
      type: "environment" as const,
      environmentCategory: "ceiling" as const,
      available: false,
      path: modelPath("environment", "gym-ceiling.glb"),
      tier: "MEDIUM" as const,
      preload: false,
      preloadPriority: 3,
    } satisfies EnvironmentAsset,
    "gym-pillars": {
      id: "gym-pillars",
      name: "Gym Pillars",
      category: "environment",
      type: "environment" as const,
      environmentCategory: "structural" as const,
      available: false,
      path: modelPath("environment", "gym-pillars.glb"),
      tier: "MEDIUM" as const,
      preload: false,
      preloadPriority: 3,
    } satisfies EnvironmentAsset,
    "gym-mirrors": {
      id: "gym-mirrors",
      name: "Gym Mirrors",
      category: "environment",
      type: "environment" as const,
      environmentCategory: "fixture" as const,
      available: false,
      path: modelPath("environment", "gym-mirrors.glb"),
      tier: "HIGH" as const,
      preload: false,
      preloadPriority: 4,
    } satisfies EnvironmentAsset,
    "gym-doors": {
      id: "gym-doors",
      name: "Gym Doors",
      category: "environment",
      type: "environment" as const,
      environmentCategory: "architecture" as const,
      available: false,
      path: modelPath("environment", "gym-doors.glb"),
      tier: "HIGH" as const,
      preload: false,
      preloadPriority: 5,
    } satisfies EnvironmentAsset,
    "gym-windows": {
      id: "gym-windows",
      name: "Gym Windows",
      category: "environment",
      type: "environment" as const,
      environmentCategory: "architecture" as const,
      available: false,
      path: modelPath("environment", "gym-windows.glb"),
      tier: "HIGH" as const,
      preload: false,
      preloadPriority: 5,
    } satisfies EnvironmentAsset,
    "gym-lighting-fixtures": {
      id: "gym-lighting-fixtures",
      name: "Lighting Fixtures",
      category: "environment",
      type: "environment" as const,
      environmentCategory: "fixture" as const,
      available: false,
      path: modelPath("environment", "gym-lighting-fixtures.glb"),
      tier: "MEDIUM" as const,
      preload: false,
      preloadPriority: 4,
    } satisfies EnvironmentAsset,
  },

  props: {} as Record<string, PropAsset>,

  hdr: {
    studio: {
      id: "hdr-studio",
      name: "Studio",
      type: "hdr" as const,
      available: false,
      path: hdrPath("studio", "studio.hdr"),
      category: "studio" as const,
      preload: false,
      preloadPriority: 2,
      intensity: 0.8,
    } satisfies HDRAsset,
    "gym-dark": {
      id: "hdr-gym-dark",
      name: "Dark Gym",
      type: "hdr" as const,
      available: false,
      path: hdrPath("dark", "gym-dark.hdr"),
      category: "dark" as const,
      preload: false,
      preloadPriority: 3,
      intensity: 0.5,
    } satisfies HDRAsset,
    "gym-dramatic": {
      id: "hdr-gym-dramatic",
      name: "Dramatic Gym",
      type: "hdr" as const,
      available: false,
      path: hdrPath("gym", "gym-dramatic.hdr"),
      category: "gym" as const,
      preload: false,
      preloadPriority: 3,
      intensity: 0.6,
    } satisfies HDRAsset,
    neutral: {
      id: "hdr-neutral",
      name: "Neutral",
      type: "hdr" as const,
      available: false,
      path: hdrPath("studio", "neutral.hdr"),
      category: "neutral" as const,
      preload: false,
      preloadPriority: 4,
      intensity: 0.7,
    } satisfies HDRAsset,
  },
} as const;

export function getAssetById(
  assetId: string,
): BaseAssetMetadata | HDRAsset | null {
  const all: (BaseAssetMetadata | HDRAsset)[] = [
    ...Object.values(assetRegistry.characters),
    ...Object.values(assetRegistry.equipment),
    ...Object.values(assetRegistry.environments),
    ...Object.values(assetRegistry.props),
    ...Object.values(assetRegistry.hdr),
  ];
  return all.find((a) => a.id === assetId) ?? null;
}

export function getPreloadQueue(): string[] {
  return [
    ...Object.values(assetRegistry.characters),
    ...Object.values(assetRegistry.equipment),
    ...Object.values(assetRegistry.environments),
    ...Object.values(assetRegistry.props),
  ]
    .filter((a) => a.available && a.preload && a.path)
    .sort((a, b) => a.preloadPriority - b.preloadPriority)
    .map((a) => a.path!);
}

export function isAssetLoadable(
  asset: BaseAssetMetadata | HDRAsset | null,
): asset is BaseAssetMetadata & { path: string } {
  return !!asset && asset.available && !!asset.path;
}
